from __future__ import annotations

import sqlite3
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DB_PATH = ROOT / "data" / "questions.sqlite"
SCHEMA_PATH = ROOT / "data" / "schema.sql"


QUESTIONS = [
    {
        "level": 1,
        "topic": "Saída",
        "difficulty": "Fácil",
        "prompt": "Qual é a saída de print(2 + 3)?",
        "options": [("5", True), ("23", False), ("Error", False)],
        "explanation": "O operador + soma dois números inteiros.",
    },
    {
        "level": 1,
        "topic": "Comentários",
        "difficulty": "Fácil",
        "prompt": "Qual símbolo inicia um comentário de uma linha em Python?",
        "options": [("//", False), ("#", True), ("/*", False)],
        "explanation": "Em Python, comentários de uma linha começam com #.",
    },
    {
        "level": 1,
        "topic": "Tipos",
        "difficulty": "Fácil",
        "prompt": "Qual é o tipo do valor '10'?",
        "options": [("int", False), ("str", True), ("float", False)],
        "explanation": "Valores entre aspas são strings.",
    },
    {
        "level": 1,
        "topic": "Variáveis",
        "difficulty": "Fácil",
        "prompt": "Qual operador é usado para atribuir valor a uma variável?",
        "options": [("==", False), ("=", True), ("=>", False)],
        "explanation": "O operador = atribui um valor; == compara valores.",
    },
    {
        "level": 1,
        "topic": "Booleanos",
        "difficulty": "Fácil",
        "prompt": "Qual é o booleano verdadeiro em Python?",
        "options": [("true", False), ("True", True), ("VERDADEIRO", False)],
        "explanation": "Python diferencia maiúsculas e minúsculas: True é o valor correto.",
    },
    {
        "level": 1,
        "topic": "Operadores",
        "difficulty": "Fácil",
        "prompt": "Qual operador faz soma?",
        "options": [("+", True), ("&", False), ("add", False)],
        "explanation": "O sinal + soma números e também concatena strings.",
    },
    {
        "level": 1,
        "topic": "Tipos",
        "difficulty": "Fácil",
        "prompt": "Qual é o resultado de type(1).__name__?",
        "options": [("int", True), ("float", False), ("str", False)],
        "explanation": "O número 1 sem casas decimais é um inteiro.",
    },
    {
        "level": 1,
        "topic": "Strings",
        "difficulty": "Fácil",
        "prompt": "Qual opção representa uma string vazia?",
        "options": [("''", True), ("None", False), ("null", False)],
        "explanation": "Duas aspas sem conteúdo formam uma string vazia.",
    },
    {
        "level": 1,
        "topic": "Entrada",
        "difficulty": "Fácil",
        "prompt": "A função input() sempre retorna qual tipo?",
        "options": [("str", True), ("int", False), ("bool", False)],
        "explanation": "input() retorna texto. Converta com int(), float() etc. quando precisar.",
    },
    {
        "level": 1,
        "topic": "Nomes",
        "difficulty": "Fácil",
        "prompt": "Qual nome de variável é válido em Python?",
        "options": [("idade_aluno", True), ("2idade", False), ("minha-idade", False)],
        "explanation": "Nomes podem ter letras, números e _, mas não podem começar com número.",
    },
    {
        "level": 1,
        "topic": "Conversão",
        "difficulty": "Fácil",
        "prompt": "Como converter a string '7' para inteiro?",
        "options": [("int('7')", True), ("str('7')", False), ("number('7')", False)],
        "explanation": "int() converte valores compatíveis para inteiro.",
    },
    {
        "level": 1,
        "topic": "Saída",
        "difficulty": "Fácil",
        "prompt": "Qual função exibe texto no terminal?",
        "options": [("print()", True), ("show()", False), ("echo()", False)],
        "explanation": "print() é a função básica para exibir valores.",
    },
    {
        "level": 1,
        "topic": "Strings",
        "difficulty": "Fácil",
        "prompt": "Qual é a saída de print('Py' + 'thon')?",
        "options": [("Python", True), ("Py thon", False), ("Error", False)],
        "explanation": "O operador + concatena strings.",
    },
    {
        "level": 1,
        "topic": "Números",
        "difficulty": "Fácil",
        "prompt": "Qual tipo representa 3.14?",
        "options": [("float", True), ("int", False), ("str", False)],
        "explanation": "Números com ponto decimal são float.",
    },
    {
        "level": 1,
        "topic": "Booleanos",
        "difficulty": "Fácil",
        "prompt": "Qual é a saída de print(bool('abc'))?",
        "options": [("True", True), ("False", False), ("Error", False)],
        "explanation": "Strings não vazias são consideradas verdadeiras.",
    },
    {
        "level": 2,
        "topic": "Listas",
        "difficulty": "Fácil",
        "prompt": "Como criar uma lista com os valores 1 e 2?",
        "options": [("(1, 2)", False), ("[1, 2]", True), ("{1, 2}", False)],
        "explanation": "Listas usam colchetes.",
    },
    {
        "level": 2,
        "topic": "Operadores",
        "difficulty": "Fácil",
        "prompt": "Qual é o resultado de 10 % 3?",
        "options": [("1", True), ("3", False), ("0", False)],
        "explanation": "% retorna o resto da divisão.",
    },
    {
        "level": 2,
        "topic": "Entrada",
        "difficulty": "Fácil",
        "prompt": "Qual função lê dados digitados pelo usuário?",
        "options": [("get()", False), ("input()", True), ("scan()", False)],
        "explanation": "input() lê texto digitado pelo usuário.",
    },
    {
        "level": 2,
        "topic": "Coleções",
        "difficulty": "Fácil",
        "prompt": "Qual função retorna a quantidade de itens de uma lista?",
        "options": [("count()", False), ("len()", True), ("size()", False)],
        "explanation": "len(lista) retorna o tamanho da coleção.",
    },
    {
        "level": 2,
        "topic": "Strings",
        "difficulty": "Fácil",
        "prompt": "Qual é a saída de print(3 * 'A')?",
        "options": [("AAA", True), ("A3", False), ("Error", False)],
        "explanation": "Multiplicar string por inteiro repete a string.",
    },
    {
        "level": 2,
        "topic": "Listas",
        "difficulty": "Fácil",
        "prompt": "Qual é o índice do primeiro item de uma lista?",
        "options": [("1", False), ("0", True), ("-1", False)],
        "explanation": "Listas em Python começam no índice 0.",
    },
    {
        "level": 2,
        "topic": "Conversão",
        "difficulty": "Fácil",
        "prompt": "Qual é o resultado de float('5')?",
        "options": [("5", False), ("5.0", True), ("'5'", False)],
        "explanation": "float() converte para número decimal.",
    },
    {
        "level": 2,
        "topic": "Condições",
        "difficulty": "Fácil",
        "prompt": "Qual palavra inicia uma condição?",
        "options": [("if", True), ("when", False), ("case", False)],
        "explanation": "if inicia um bloco condicional em Python.",
    },
    {
        "level": 2,
        "topic": "Comparação",
        "difficulty": "Fácil",
        "prompt": "Qual operador testa igualdade?",
        "options": [("=", False), ("==", True), ("===", False)],
        "explanation": "== compara se dois valores são iguais.",
    },
    {
        "level": 2,
        "topic": "Strings",
        "difficulty": "Fácil",
        "prompt": "Qual método deixa uma string em maiúsculas?",
        "options": [(".upper()", True), (".big()", False), (".caps()", False)],
        "explanation": "upper() retorna uma versão em maiúsculas.",
    },
    {
        "level": 2,
        "topic": "Listas",
        "difficulty": "Fácil",
        "prompt": "Como acessar o segundo item de L?",
        "options": [("L[1]", True), ("L[2]", False), ("L.second()", False)],
        "explanation": "Como o primeiro índice é 0, o segundo item está em L[1].",
    },
    {
        "level": 2,
        "topic": "Condições",
        "difficulty": "Fácil",
        "prompt": "Qual palavra é usada para o caso contrário em um if?",
        "options": [("else", True), ("otherwise", False), ("default", False)],
        "explanation": "else executa quando a condição anterior é falsa.",
    },
    {
        "level": 2,
        "topic": "Operadores",
        "difficulty": "Fácil",
        "prompt": "Qual é o resultado de 2 ** 3?",
        "options": [("6", False), ("8", True), ("9", False)],
        "explanation": "** calcula potência.",
    },
    {
        "level": 2,
        "topic": "Strings",
        "difficulty": "Fácil",
        "prompt": "Qual método remove espaços no começo e no fim de uma string?",
        "options": [(".strip()", True), (".trim()", False), (".clean()", False)],
        "explanation": "strip() remove espaços e quebras nas pontas.",
    },
    {
        "level": 2,
        "topic": "Listas",
        "difficulty": "Fácil",
        "prompt": "Qual método adiciona item ao final de uma lista?",
        "options": [(".append()", True), (".push()", False), (".addEnd()", False)],
        "explanation": "append() adiciona um item no fim da lista.",
    },
    {
        "level": 3,
        "topic": "Comparação",
        "difficulty": "Médio",
        "prompt": "Qual operador significa diferente de?",
        "options": [("!=", True), ("<>", False), ("not=", False)],
        "explanation": "!= testa se dois valores são diferentes.",
    },
    {
        "level": 3,
        "topic": "Loops",
        "difficulty": "Médio",
        "prompt": "O que range(3) gera em um for?",
        "options": [("1, 2, 3", False), ("0, 1, 2", True), ("0, 1, 2, 3", False)],
        "explanation": "range(3) começa em 0 e para antes do 3.",
    },
    {
        "level": 3,
        "topic": "Lógica",
        "difficulty": "Médio",
        "prompt": "Qual operador representa E lógico?",
        "options": [("&&", False), ("and", True), ("&", False)],
        "explanation": "and combina duas condições booleanas.",
    },
    {
        "level": 3,
        "topic": "Funções",
        "difficulty": "Médio",
        "prompt": "Como definir uma função chamada soma?",
        "options": [("def soma():", True), ("function soma():", False), ("void soma():", False)],
        "explanation": "Funções em Python são definidas com def.",
    },
    {
        "level": 3,
        "topic": "Loops",
        "difficulty": "Médio",
        "prompt": "Qual palavra interrompe um loop?",
        "options": [("exit", False), ("stop", False), ("break", True)],
        "explanation": "break encerra o loop atual.",
    },
    {
        "level": 3,
        "topic": "Booleanos",
        "difficulty": "Médio",
        "prompt": "Qual é o resultado de bool(0)?",
        "options": [("True", False), ("False", True), ("None", False)],
        "explanation": "O número zero é considerado falso.",
    },
    {
        "level": 3,
        "topic": "Listas",
        "difficulty": "Médio",
        "prompt": "Como testar se 5 está na lista L?",
        "options": [("5 in L", True), ("L.has(5)", False), ("L.exists(5)", False)],
        "explanation": "O operador in testa pertencimento.",
    },
    {
        "level": 3,
        "topic": "Loops",
        "difficulty": "Médio",
        "prompt": "Qual palavra pula para a próxima repetição do loop?",
        "options": [("continue", True), ("skip", False), ("next", False)],
        "explanation": "continue pula o restante da iteração atual.",
    },
    {
        "level": 3,
        "topic": "Funções",
        "difficulty": "Médio",
        "prompt": "Qual palavra devolve um valor de uma função?",
        "options": [("return", True), ("send", False), ("yieldall", False)],
        "explanation": "return encerra a função e devolve um valor.",
    },
    {
        "level": 3,
        "topic": "Escopo",
        "difficulty": "Médio",
        "prompt": "Uma variável criada dentro de uma função normalmente tem qual escopo?",
        "options": [("local", True), ("global", False), ("público", False)],
        "explanation": "Variáveis criadas dentro da função são locais por padrão.",
    },
    {
        "level": 3,
        "topic": "Listas",
        "difficulty": "Médio",
        "prompt": "Qual expressão copia todos os itens de L em uma nova lista?",
        "options": [("L[:]", True), ("L[]", False), ("copy L", False)],
        "explanation": "O fatiamento L[:] cria uma cópia rasa da lista.",
    },
    {
        "level": 3,
        "topic": "Strings",
        "difficulty": "Médio",
        "prompt": "Qual é o resultado de 'python'.capitalize()?",
        "options": [("Python", True), ("PYTHON", False), ("python", False)],
        "explanation": "capitalize() coloca a primeira letra em maiúscula.",
    },
    {
        "level": 3,
        "topic": "Erros",
        "difficulty": "Médio",
        "prompt": "Qual bloco captura exceções?",
        "options": [("try/except", True), ("if/error", False), ("catch/error", False)],
        "explanation": "try/except é usado para tratar exceções em Python.",
    },
    {
        "level": 3,
        "topic": "Dicionários",
        "difficulty": "Médio",
        "prompt": "Como acessar o valor da chave 'nome' em d?",
        "options": [("d['nome']", True), ("d.nome", False), ("d->nome", False)],
        "explanation": "Dicionários acessam chaves com colchetes.",
    },
    {
        "level": 3,
        "topic": "Funções",
        "difficulty": "Médio",
        "prompt": "O que significa um parâmetro com valor padrão?",
        "options": [("Pode ser omitido na chamada", True), ("É obrigatório", False), ("Nunca muda", False)],
        "explanation": "Parâmetros com valor padrão são usados quando a chamada não informa um valor.",
    },
    {
        "level": 4,
        "topic": "Strings",
        "difficulty": "Médio",
        "prompt": "Qual é o resultado de 'Python'[0]?",
        "options": [("P", True), ("y", False), ("n", False)],
        "explanation": "O índice 0 acessa o primeiro caractere.",
    },
    {
        "level": 4,
        "topic": "Listas",
        "difficulty": "Médio",
        "prompt": "Como acessar o último item de L?",
        "options": [("L[last]", False), ("L[-1]", True), ("L[0]", False)],
        "explanation": "Índices negativos contam do final da lista.",
    },
    {
        "level": 4,
        "topic": "Listas",
        "difficulty": "Médio",
        "prompt": "Como remover e retornar o item no índice i?",
        "options": [("L.pop(i)", True), ("L.remove(i)", False), ("del(L)", False)],
        "explanation": "pop(i) remove e retorna o item daquele índice.",
    },
    {
        "level": 4,
        "topic": "Operadores",
        "difficulty": "Médio",
        "prompt": "Qual é o valor de 10 // 3?",
        "options": [("3.33", False), ("3", True), ("1", False)],
        "explanation": "// faz divisão inteira.",
    },
    {
        "level": 4,
        "topic": "Dicionários",
        "difficulty": "Médio",
        "prompt": "Qual literal cria um dicionário vazio?",
        "options": [("{}", True), ("[]", False), ("()", False)],
        "explanation": "{} cria um dicionário vazio.",
    },
    {
        "level": 4,
        "topic": "Tuplas",
        "difficulty": "Médio",
        "prompt": "Qual é o tipo de (1, 2)?",
        "options": [("list", False), ("tuple", True), ("dict", False)],
        "explanation": "Parênteses com valores separados por vírgula formam tupla.",
    },
    {
        "level": 4,
        "topic": "Strings",
        "difficulty": "Médio",
        "prompt": "Qual opção é uma f-string válida?",
        "options": [("f'Oi {nome}'", True), ("'Oi %nome'", False), ("format'Oi {nome}'", False)],
        "explanation": "f-strings começam com f antes das aspas.",
    },
    {
        "level": 4,
        "topic": "Dicionários",
        "difficulty": "Médio",
        "prompt": "Qual método retorna pares chave/valor de um dicionário?",
        "options": [(".items()", True), (".pairs()", False), (".values_keys()", False)],
        "explanation": "items() retorna uma visão com pares chave/valor.",
    },
    {
        "level": 4,
        "topic": "Arquivos",
        "difficulty": "Médio",
        "prompt": "Qual modo abre arquivo para leitura?",
        "options": [("'r'", True), ("'w'", False), ("'a'", False)],
        "explanation": "O modo 'r' abre o arquivo para leitura.",
    },
    {
        "level": 4,
        "topic": "List comprehension",
        "difficulty": "Médio",
        "prompt": "Qual expressão cria [0, 1, 2]?",
        "options": [("[x for x in range(3)]", True), ("[x for range(3)]", False), ("list(1,2,3)", False)],
        "explanation": "A list comprehension percorre range(3) e guarda cada x.",
    },
    {
        "level": 4,
        "topic": "Módulos",
        "difficulty": "Médio",
        "prompt": "Como importar o módulo math?",
        "options": [("import math", True), ("using math", False), ("include math", False)],
        "explanation": "import carrega módulos em Python.",
    },
    {
        "level": 4,
        "topic": "Sets",
        "difficulty": "Médio",
        "prompt": "Qual estrutura não permite itens duplicados?",
        "options": [("set", True), ("list", False), ("tuple", False)],
        "explanation": "set representa conjunto e elimina duplicatas.",
    },
    {
        "level": 4,
        "topic": "Funções",
        "difficulty": "Médio",
        "prompt": "O que *args permite em uma função?",
        "options": [("Receber vários argumentos posicionais", True), ("Forçar inteiro", False), ("Criar variável global", False)],
        "explanation": "*args empacota argumentos posicionais extras em uma tupla.",
    },
    {
        "level": 4,
        "topic": "Dicionários",
        "difficulty": "Médio",
        "prompt": "Qual método busca uma chave sem gerar erro se ela não existir?",
        "options": [(".get()", True), (".find()", False), (".safe()", False)],
        "explanation": "get() retorna None ou um valor padrão quando a chave não existe.",
    },
    {
        "level": 4,
        "topic": "Erros",
        "difficulty": "Médio",
        "prompt": "Qual exceção aparece ao acessar índice inexistente em uma lista?",
        "options": [("IndexError", True), ("KeyError", False), ("NameError", False)],
        "explanation": "IndexError indica índice fora do intervalo.",
    },
    {
        "level": 5,
        "topic": "List comprehension",
        "difficulty": "Difícil",
        "prompt": "Qual é o resultado de [x * 2 for x in range(3)]?",
        "options": [("[0, 2, 4]", True), ("[2, 4, 6]", False), ("[0, 1, 2]", False)],
        "explanation": "range(3) gera 0, 1 e 2; cada valor é multiplicado por 2.",
    },
    {
        "level": 5,
        "topic": "None",
        "difficulty": "Difícil",
        "prompt": "Qual é type(None).__name__?",
        "options": [("NoneType", True), ("null", False), ("void", False)],
        "explanation": "None é o único valor do tipo NoneType.",
    },
    {
        "level": 5,
        "topic": "Fatiamento",
        "difficulty": "Difícil",
        "prompt": "Se L = [10, 20, 30], qual é L[:2]?",
        "options": [("[10, 20]", True), ("[20, 30]", False), ("[10, 20, 30]", False)],
        "explanation": "L[:2] pega do início até antes do índice 2.",
    },
    {
        "level": 5,
        "topic": "Erros",
        "difficulty": "Difícil",
        "prompt": "Qual erro ocorre em 10 / 0?",
        "options": [("ZeroDivisionError", True), ("DivError", False), ("MathError", False)],
        "explanation": "Divisão por zero gera ZeroDivisionError.",
    },
    {
        "level": 5,
        "topic": "Listas",
        "difficulty": "Difícil",
        "prompt": "Qual método remove todos os itens de uma lista L?",
        "options": [("L.clear()", True), ("L.delete()", False), ("L.empty()", False)],
        "explanation": "clear() limpa a lista sem criar outra.",
    },
    {
        "level": 5,
        "topic": "Geradores",
        "difficulty": "Difícil",
        "prompt": "Qual palavra produz valores aos poucos em uma função geradora?",
        "options": [("yield", True), ("return all", False), ("emit", False)],
        "explanation": "yield pausa a função e entrega um valor por vez.",
    },
    {
        "level": 5,
        "topic": "Lambda",
        "difficulty": "Difícil",
        "prompt": "Qual expressão cria uma função que soma 1?",
        "options": [("lambda x: x + 1", True), ("lambda x => x + 1", False), ("fn x: x + 1", False)],
        "explanation": "lambda cria funções pequenas em uma expressão.",
    },
    {
        "level": 5,
        "topic": "Classes",
        "difficulty": "Difícil",
        "prompt": "Qual método inicializa atributos de uma classe?",
        "options": [("__init__", True), ("__start__", False), ("constructor", False)],
        "explanation": "__init__ é chamado ao criar uma instância.",
    },
    {
        "level": 5,
        "topic": "Classes",
        "difficulty": "Difícil",
        "prompt": "O que self representa dentro de um método de instância?",
        "options": [("A própria instância", True), ("A classe pai", False), ("Uma variável global", False)],
        "explanation": "self aponta para o objeto atual.",
    },
    {
        "level": 5,
        "topic": "Context manager",
        "difficulty": "Difícil",
        "prompt": "Por que usar with open('a.txt') as f?",
        "options": [("Para fechar o arquivo automaticamente", True), ("Para acelerar o processador", False), ("Para transformar texto em lista", False)],
        "explanation": "with garante o fechamento adequado do arquivo.",
    },
    {
        "level": 5,
        "topic": "Dicionários",
        "difficulty": "Difícil",
        "prompt": "Qual é o resultado de {'a': 1}.get('b', 0)?",
        "options": [("0", True), ("None", False), ("KeyError", False)],
        "explanation": "get retorna o valor padrão quando a chave não existe.",
    },
    {
        "level": 5,
        "topic": "Compreensões",
        "difficulty": "Difícil",
        "prompt": "Qual expressão cria um dicionário com quadrados de 0 a 2?",
        "options": [("{x: x*x for x in range(3)}", True), ("[x: x*x for x in range(3)]", False), ("dict(x*x for x in range(3))", False)],
        "explanation": "Compreensão de dicionário usa chaves e pares chave: valor.",
    },
    {
        "level": 5,
        "topic": "Exceções",
        "difficulty": "Difícil",
        "prompt": "Qual bloco sempre executa em um try/except?",
        "options": [("finally", True), ("always", False), ("end", False)],
        "explanation": "finally executa havendo erro ou não.",
    },
    {
        "level": 5,
        "topic": "Iteradores",
        "difficulty": "Difícil",
        "prompt": "Qual função obtém o próximo item de um iterador?",
        "options": [("next()", True), ("move()", False), ("take()", False)],
        "explanation": "next(iterador) pede o próximo valor disponível.",
    },
    {
        "level": 5,
        "topic": "Ordenação",
        "difficulty": "Difícil",
        "prompt": "Qual argumento permite ordenar uma lista de dicionários por uma chave?",
        "options": [("key", True), ("index", False), ("where", False)],
        "explanation": "sorted(..., key=...) define a regra usada na ordenação.",
    },
]


def initialize_database() -> None:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)

    with sqlite3.connect(DB_PATH) as connection:
        connection.executescript(SCHEMA_PATH.read_text(encoding="utf-8"))
        connection.execute("DELETE FROM question_options")
        connection.execute("DELETE FROM questions")

        for question in QUESTIONS:
            cursor = connection.execute(
                """
                INSERT INTO questions (level, topic, difficulty, prompt, explanation, active)
                VALUES (?, ?, ?, ?, ?, 1)
                """,
                (
                    question["level"],
                    question["topic"],
                    question["difficulty"],
                    question["prompt"],
                    question["explanation"],
                ),
            )
            question_id = cursor.lastrowid

            for sort_order, (text, is_correct) in enumerate(question["options"]):
                connection.execute(
                    """
                    INSERT INTO question_options (question_id, text, is_correct, sort_order)
                    VALUES (?, ?, ?, ?)
                    """,
                    (question_id, text, int(is_correct), sort_order),
                )


if __name__ == "__main__":
    initialize_database()
    print(f"Banco criado em: {DB_PATH}")
    print(f"Questões inseridas: {len(QUESTIONS)}")
